---
- name: start cron
  service: name=cron state=started

- name: ensure cron log
  action: file dest=/var/www/{{ site_url }}/log state=directory owner={{ ansible_ssh_user }} group=www-data mode=0775 recurse=yes

- name: setup cron plugmy:replug:bumporder
  cron: name="plugmy:replug:bumporder"
        minute="15"
        hour="0"
        weekday="*"
        job="/var/www/{{ site_url }}/src/app/console plugmy:replug:bumporder --env={{ env }} >> /var/www/{{ site_url }}/log/cron.log 2>&1"

- name: setup cron plugmy:reminder:email --queue
  cron: name="plugmy:reminder:email --queue"
        minute="1"
        hour="23"
        weekday="*"
        job="/var/www/{{ site_url }}/src/app/console plugmy:reminder:email --queue --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:reminder:email --send
  cron: name="plugmy:reminder:email --send"
        minute="1"
        hour="6,15"
        weekday="*"
        job="/var/www/{{ site_url }}/src/app/console plugmy:reminder:email --send --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:allplugs:send --weekly
  cron: name="plugmy:allplugs:send --weekly"
        minute="5"
        hour="23"
        weekday="6"
        job="/var/www/{{ site_url }}/src/app/console plugmy:allplugs:send --weekly --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:hotplugs:send --weekly
  cron: name="plugmy:hotplugs:send --weekly"
        minute="5"
        hour="23"
        weekday="6"
        job="/var/www/{{ site_url }}/src/app/console plugmy:hotplugs:send --weekly --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:interestplugs:send --weekly
  cron: name="plugmy:interestplugs:send --weekly" minute="5"
        hour="23"
        weekday="6"
        job="/var/www/{{ site_url }}/src/app/console plugmy:interestplugs:send --weekly --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:randomplugs:send --weekly
  cron: name="plugmy:randomplugs:send --weekly"
        minute="5"
        hour="23"
        weekday="6"
        job="/var/www/{{ site_url }}/src/app/console plugmy:randomplugs:send --weekly --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:plugoftheday:send --weekly
  cron: name="plugmy:plugoftheday:send --weekly"
        minute="5"
        hour="23"
        weekday="6"
        job="/var/www/{{ site_url }}/src/app/console plugmy:plugoftheday:send --weekly --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:allplugs:send --daily
  cron: name="plugmy:allplugs:send --daily"
        minute="5"
        hour="21"
        weekday="*"
        job="/var/www/{{ site_url }}/src/app/console plugmy:allplugs:send --daily --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:hotplugs:send --daily
  cron: name="plugmy:hotplugs:send --daily"
        minute="5"
        hour="21"
        weekday="*"
        job="/var/www/{{ site_url }}/src/app/console plugmy:hotplugs:send --daily --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:interestplugs:send --daily
  cron: name="plugmy:interestplugs:send --daily"
        minute="5"
        hour="21"
        weekday="*"
        job="/var/www/{{ site_url }}/src/app/console plugmy:interestplugs:send --daily --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:randomplugs:send --daily
  cron: name="plugmy:randomplugs:send --daily"
        minute="5"
        hour="21"
        weekday="*"
        job="/var/www/{{ site_url }}/src/app/console plugmy:randomplugs:send --daily --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:plugoftheday:send --daily
  cron: name="plugmy:plugoftheday:send --daily"
        minute="5"
        hour="21"
        weekday="*"
        job="/var/www/{{ site_url }}/src/app/console plugmy:plugoftheday:send --daily --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:newplugs:send --weekly
  cron: name="plugmy:newplugs:send --weekly"
        minute="*/5"
        hour="23"
        weekday="6"
        job="/var/www/{{ site_url }}/src/app/console plugmy:newplugs:send --weekly --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"

- name: setup cron plugmy:newplugs:send --daily
  cron: name="plugmy:newplugs:send --daily"
        minute="*/5"
        hour="21"
        weekday="*"
        job="/var/www/{{ site_url }}/src/app/console plugmy:newplugs:send --daily --env={{ env }} >> /var/www/{{ site_url }}/log/cron_mail.log 2>&1"