---
- name: use ondrej/php5-5.6 repo
  apt_repository: repo=ppa:ondrej/php5-5.6 update_cache=yes

- name: install php packages
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-cli
    - php5-fpm
    - php5-common
    - php5-curl
    - php5-dev
    - php5-gd
    - php5-mysql
    - php5-mcrypt

- name: setup php cli config
  template: src=php.ini dest=/etc/php5/cli/php.ini

- name: setup php fpm config
  template: src=php.ini dest=/etc/php5/fpm/php.ini
  notify: restart php-fpm

- name: setup fpm pool config
  template: src=www.conf dest=/etc/php5/fpm/pool.d/www.conf
  notify: restart php-fpm


#- name: setup php apache config
#  template: src=php.ini dest=/etc/php5/apache2/php.ini
#  notify: restart apache2


#- name: xdebug ensure log directory
#  action: file dest=/var/log/xdebug state=directory owner=www-data group=www-data
#  when: env != 'dev'
#
#- name: setup xdebug config
#  template: src=20-xdebug.ini dest=/etc/php5/fpm/conf.d/20-xdebug.ini
#  notify: restart php-fpm
#  when: env == 'dev'
#
#- name: install php dev packages
#  apt: pkg={{ item }} state=latest
#  with_items:
#    - php5-xdebug
#  when: env == 'dev'